### ISSUE TITLE
Use about URI scheme

### ISSUE THREAD

**Issue by filips123** [cookiengineer/stealth-browser#14]
> about is an internal URI scheme implemented in various Web browsers to reveal internal state and built-in functions. It is an IANA officially registered scheme, and is standardized.

Currently, Stealth only supports `stealth` URI scheme. It would be good if it would also support standaralized `about` URI scheme. That URIs should probably be translated into the appropriate `stealth` URIs.

Complete list of all about URIs is on [Wikipedia](https://en.wikipedia.org/wiki/About_URI_scheme).

**Comment by cookiengineer** [comment]
While I like the idea of supporting the `about:` scheme for migrating users, I don't like where the scheme is going because the standardized part behind it is somewhat a joke and everything is still custom across all Browsers.

The problem with the `about:` scheme is that they basically exist for blank documents and cross-origin-resource-sharing aspects of e.g. iframes. While they make sense in the context of a native browser that renders its own iframe implementations; I don't think that they would make sense in Stealth, as the iframe always points to a document that is being served by the node.js service.

The problem I additionally have with `about:` is the potential fuckups when URIs are mapped to stealth pages and are forgotten later. They are strictly a UI feature, so they are hard to test (if even possible).

The only about pages that would make sense (somewhat) are these:

- `about:blank` -> pointing to empty iframe.
- `about:invalid` -> pointing to `stealth:fix-request` but without a URL, so wouldn't make sense (don't want to go the `Referer` history route due to privacy concerns).
- `about:cache` -> pointing to `stealth:cache`.

... as this is missing all the fix-wizards for specific use cases I don't see the point in implementing it at the moment.

I think considering something like a UI overlay that guides the user to find the "internal page" they want to via e.g. a search overlay would make more sense; similar to what pressing 3 times ESCAPE in a row does.
