### ISSUE TITLE
Black settings

### ISSUE THREAD

**Issue by hissssst** [cookiengineer/stealth-browser#42]
## Description

Settings page font (or maybe all page) is black.

## Desired behaviour

It would be nice to have some readable text

## Actual behaviour
![scrot_200727230036](https://user-images.githubusercontent.com/37012324/88586480-fa5ce680-d043-11ea-906d-89fa9b4f0eec.png)

## Steps to reproduce

Clone master
Follow quickstart guide
Open settings

## Enviroment

```
ChromeDriver 83.0.4103.116 (8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716})
```

**Comment by cookiengineer** [comment]
Yes, this is correct.

Currently, the `stealth:settings` are broken due to a Design/UI Refactor that's been going on since the Element/Widget API refactor ( https://github.com/tholian-network/stealth/commit/40e9efc3348381c1985a92fbea5a5eaec1faedfb ) that led to a cleaner element-driven design across the Browser UI.

So far, most of the Browser's Main UI has been ported to the new Widget API (`appbar`, `backdrop`, `sheet`, `menu` etc.) though the Elements necessary for the Service integration are still missing.

I've opened up an issue that's tracking this at https://github.com/tholian-network/stealth/issues/44

**Comment by cookiengineer** [comment]
Currently, the `stealth:settings` are broken due to an ongoing refactor since the Element/Widget API change (somewhere around https://github.com/tholian-network/stealth/commit/40e9efc3348381c1985a92fbea5a5eaec1faedfb ) that led to a cleaner element-driven design across the Browser UI.

So far, most of the Browser's Main UI has been ported to the new Widget API (meaning the `appbar`, `backdrop`, `menu`, `sheet` Widgets with exception to the Webview's `dispatch()` handler for Context Menu integration) though the ones necessary for the Stealth Service are still missing.

As the new UI will have a Redux-like state management, most parts of the old settings page will get unnecessary as those Widgets will manage their states themselves, so that outside cache/settings management isn't necessary anymore.

I've opened up an issue that's tracking the UI refactor progress at https://github.com/tholian-network/stealth/issues/44

**Comment by cookiengineer** [comment]
As of https://github.com/tholian-network/stealth/commit/eb66b3910c51ad9ec7ef0c29e01585a792808958 most parts of the Settings have been migrated.

The Session card and Tab card doesn't work yet, but is tracked in another issue.
